version: '3.8'

x-base-config: &base_config
  image: timberio/vector:0.42.X-debian
  restart: always
  deploy:
    resources:
      limits:
        cpus: '1.0'
        memory: 512M
  command:
    - '-t'
    - '1'


services:
  k8s_app_log:
    <<: *base_config
    volumes:
      - ${PWD}/conf/k8s_app_log.yaml:/etc/vector/vector.yaml
  k8s_app_file_log:
    <<: *base_config
    volumes:
      - ${PWD}/conf/k8s_app_file_log.yaml:/etc/vector/vector.yaml