sources:
  kafka-prod:
    type: kafka
    auto_offset_reset: earliest
    bootstrap_servers: alikafka-post-public-intl-sg-4hr2ybawh02-1-vpc.alikafka.aliyuncs.com:9092
    topics:
      - nginx_log.prod
    group_id: k2ch-nginx_log
    decoding:
      codec: json
transforms:
  filtering:
    type: filter
    inputs:
     - kafka-prod
    condition: exists(.data.url) && .data.url != "/metrics"
  remapping:
    type: remap
    inputs:
      - filtering
    drop_on_error: true
    reroute_dropped: true
    source: |-
      . = .data
      .ts = parse_timestamp!(._time_, "%+")
      .path = del(.url)
      .user_agent = slice!(del(.http_user_agent), 0, 100)
      .bytes_sent = parse_int!(.body_bytes_sent)
      .client_ip = if (.x_forward_for != "") { .x_forward_for } else { .remote_addr }
      .request_time = parse_float!(.request_time)
      .request_length = parse_int!(.request_length)
      .referer = del(.http_referer)
      .status = parse_int!(.status)
      .upstream_name = del(.proxy_upstream_name)
      .upstream_status, err = parse_int(.upstream_status)
      if err != null {
        .upstream_status = -1
      }
      .upstream_response_time, err = parse_float(.upstream_response_time)
      if err != null {
        .upstream_response_time = -1
      }
      .upstream_response_length, err = parse_int(.upstream_response_length)
      if err != null {
        .upstream_response_length = -1
      }
sinks:
  devops-ch:
    type: clickhouse
    inputs:
      - remapping
    endpoint: "http://10.0.1.112:8123"
    database: ops
    table: nginx_log
    skip_unknown_fields: true
    date_time_best_effort: true
  stdout:
    type: console
    inputs:
      - '*.dropped'
    encoding:
      codec: json